config/routes.rb
Blog::Application.routes.draw do

  resources :posts, path: 'blog'

  get '/blog/:permalink' => 'posts#show', as: :permalink

  get '/login' => 'sessions#new', as: :login
  get '/logout' => 'sessions#destroy', as: :logout
  post '/sessions' => 'sessions#create'
  get '/resume' => 'pages#resume', as: :resume

  root to: 'pages#home'

  get "*path" => redirect('/') unless Rails.env.development?

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :logged_in?

  def logged_in?
    session[:user_id].present?
  end

  def require_login
    unless logged_in?
      redirect_to root_path
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @posts = Post.all.order('created_at DESC')[0..4]
  end

  def resume
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:edit, :update, :destroy]
  before_action :permalink_params, only: :show
  before_action :require_login, only: [:new, :edit, :update, :destroy]

  layout 'blog'

  def index
    @posts = Post.all.order('created_at DESC')
  end

  def show
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to permalink_path(permalink: @post.permalink), notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to permalink_path(permalink: @post.permalink), notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :permalink)
    end

    def permalink_params
      params.permit(:id)
      @post = Post.find_by(permalink: params[:id])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def destroy
    reset_session
    redirect_to root_url, notice: "See ya!"
  end

  def create
    user = User.find_by(email: params[:email])
    if user.present?
      if user.authenticate(params[:password])
        session[:user_id] = user.id
        redirect_to root_url, notice: "Hello, #{user.email}"
      else
        flash.now[:notice] = "Please try again."
        render 'new'
      end
    else
      flash.now[:notice] = "Please try again."
      render 'new'
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_login, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password_digest)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def markdown
    Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, space_after_headers: true)
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class='ie6' lang='en'> <![endif]-->
<!--[if IE 7 ]>    <html class='ie7' lang='en'> <![endif]-->
<!--[if IE 8 ]>    <html class='ie8' lang='en'> <![endif]-->
<!--[if IE 9 ]>    <html class='ie9' lang='en'> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang='en'> <!--<![endif]-->
  <head>
  	<meta charset='utf-8' />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv='X-UA-Compatible' content='IE=7' /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name='viewport' content='width=device-width, initial-scale=1.0' />

  	<title><%= content_for?(:title) ? yield(:title) : 'Vincent Cabansag' %></title>

  	<%= stylesheet_link_tag    'application' %>
  	<%= javascript_include_tag 'vendor/custom.modernizr' %>

    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

    <%= csrf_meta_tags %>
  </head>

  <body>
    <p id="notice"><%= notice %></p>
      <%= yield %>
      <% if logged_in?  %>
        <%= link_to 'Logout', logout_path %>
      <% end %>
    </div>
    <%= javascript_include_tag 'application' %>
  </body>

</html>

app/views/layouts/blog.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class='ie6' lang='en'> <![endif]-->
<!--[if IE 7 ]>    <html class='ie7' lang='en'> <![endif]-->
<!--[if IE 8 ]>    <html class='ie8' lang='en'> <![endif]-->
<!--[if IE 9 ]>    <html class='ie9' lang='en'> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang='en'> <!--<![endif]-->

  <head>
  	<meta charset='utf-8' />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv='X-UA-Compatible' content='IE=7' /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name='viewport' content='width=device-width, initial-scale=1.0' />
  	<title><%= content_for?(:title) ? yield(:title) : 'The Blog of Vincent Cabansag' %></title>

  	<%= stylesheet_link_tag    'application' %>
  	<%= javascript_include_tag 'vendor/custom.modernizr' %>

    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'favicon.gif' %>
  </head>

  <body>
    <div class='row'>
      <div class='show-for-small small-12 small-centered columns photo-header'>
        <div class='row'>
          <div class='small-11 small-centered text-center columns'>
            You're reading the <%= link_to 'blog', posts_path %> of <%= link_to 'Vincent Cabansag', root_path %>.
          </div>
        </div>
      </div>
      <div class='show-for-medium small-9 small-centered text-center columns photo-header'>
        <%= image_tag 'profile-photo.jpg', class: 'profile-photo small' %>You're reading the <%= link_to 'blog', posts_path %> of <%= link_to 'Vincent Cabansag', root_path %>.
      </div>
      <div class='show-for-large-up large-6 large-centered columns photo-header'>
        <%= image_tag 'profile-photo.jpg', class: 'profile-photo small' %>You're reading the <%= link_to 'blog', posts_path %> of <%= link_to 'Vincent Cabansag', root_path %>.
      </div>
    </div>
    <div class='row'>
      <p id='notice'><%= notice %></p>
      <%= yield %>
      <% if logged_in?  %>
        <%= link_to 'Logout', logout_path %>
      <% end %>
    </div>
    <%= javascript_include_tag 'application' %>
  </body>

</html>

app/views/pages/home.html.erb
<div class='row'>
  <div class='small-12 large-12 columns'>

    <div class='row'>
      <div class='show-for-small small-12 columns text-left greeting-small'>
        <%= image_tag 'profile-photo.jpg', class: 'profile-photo-small text-center' %>
          Hi, I'm Vincent Cabansag. I'm an entrepreneur, developer and photographer.
          I'm the Director of Operations at <a href='http://matterchicago.com' title='MATTER Chicago'>MATTER Chicago</a> and
          I also love traveling and taking
          <a href='http://instagram.com/vcabansag' title='vcabansag on Instagram'>photos</a>.
      </div>
      <div class='show-for-medium large-10 large-offset-2 columns text-left greeting-large'>
        <%= image_tag 'profile-photo.jpg', class: 'profile-photo-large text-center' %>
        <div class='large-8 greeting-text-large'>
          Hi, I'm Vincent Cabansag. I'm an entrepreneur, developer and photographer.
          I'm the Director of Operations at <a href='http://matterchicago.com' title='MATTER Chicago'>MATTER Chicago</a> and
          I also love traveling and taking
          <a href='http://instagram.com/vcabansag' title='vcabansag on Instagram'>photos</a>.
        </div>
      </div>
      <div class='show-for-large-up large-10 large-offset-2 columns text-left greeting-large'>
        <%= image_tag 'profile-photo.jpg', class: 'profile-photo-large text-center' %>
        <div class='large-8 greeting-text-large'>
          Hi, I'm Vincent Cabansag. I'm an entrepreneur, developer and photographer.
          I'm the Director of Operations at <a href='http://matterchicago.com' title='MATTER Chicago'>MATTER Chicago</a> and
          I also love traveling and taking
          <a href='http://instagram.com/vcabansag' title='vcabansag on Instagram'>photos</a>.
        </div>
      </div>
    </div>

    <div class='row'>
      <div class='latest small-12 large-5 large-offset-2 columns'>
        <h5>Latest posts</h5>
        <ul class='no-bullet'>
          <% @posts.each do |post| %>
            <li><%= link_to post.title, permalink_path(permalink: post.permalink) %></li>
          <% end %>
        </ul>
      </div>
      <div class='about small-12 large-5 columns'>
        <h5>About me</h5>
        <ul class='no-bullet'>
          <li>Read my blog <%= link_to 'here', posts_path %></li>
          <li>See my latest photos on <%= link_to 'Instagram', 'http://instagram.com/vcabansag' %></li>
          <li>Follow me on Twitter at <%= link_to '@vcabansag', 'https://twitter.com/vcabansag' %></li>
          <li>Contact me at <%= mail_to 'vcabansag@gmail.com' %></li>
        </ul>
      </div>
    </div>

  </div>
</div>

app/views/pages/resume.html.erb
<div class='row resume-page'>

  <div class='small-1 large-2 columns'>
  </div>

  <div class='small-10 small-offset-1 large-8 large-offset-2 columns'>

    <h1>Vincent Cabansag</h1>

    <h5 class='subheader'>
      <p>
        I'm a developer, designer and entrepreneur who excels at managing projects from beginning to end.
        My experience spans operations, education, real estate, compliance, sales, marketing, web development,
        IT and business development.
      </p>
      <p>
        As of July 10, 2015, I'm looking for a growing company where I can add value
        and do my best work to date.
      </p>
      <p>
        My ideal outcome is to lead a team in the role of a COO or CTO.
      </p>
    </h5>

    <h4>Contact me</h4>
    <p>Email me at <%= mail_to 'vcabansag@gmail.com' %> or call me at (312) 546-3985.</p>

    <h4>Skills</h4>

    <h6>Leadership</h6>
    <p>
      When I lead a team, I bring out the best in them by setting clear
      expectations, measurable goals and understanding their capabilities.
    </p>

    <h6>Entrepreneurship</h6>
    <p>
      I've helped two early-stage companies scale their operations over the past decade.
      I know how to create a workplace that's lean, resourceful and feedback-oriented.
    </p>

    <h6>Project Management</h6>
    <p>
      I've led projects that range from real estate, compliance, IT,
      and web development. I know to develop work relationships that are effective and results-driven.
    </p>

    <h6>Creation</h6>
    <p>
      I have the technical skills to design, code and ship a web application.
      I strive to be a better writer and I have the skill to take professional quality photos.
    </p>

    <h4>Experience</h4>

    <h6>The Starter League</h6>
    <p>
      <em>Director of Operations, Chicago, IL, 2011 &mdash; 2015</em>
    </p>
    <p>
      <%= link_to 'The Starter League', 'http://www.starterleague.com/' %> is a school that
      teaches people how to code, design and build web applications. It's the first of its
      kind and I was part of the inaugural class. I loved it so much, that I joined the founders
      in January 2012 to help scale operations. I'm proud to have helped the company rebrand itself,
      relocate to a new workspace and become a licensed school with the Illinois Board of Higher
      Education.
    </p>

    <p>
      Here's what I did on any given day:
    </p>

    <ul class="push-1">
      <li>led team meetings and stand-ups</li>
      <li>managed financials with the company's controller</li>
      <li>created and streamlined processes</li>
      <li>recruited and developed talent
      <li>hired and on-boarded personnel</li>
      <li>supervised facility management</li>
      <li>helped with change management</li>
      <li>maintained information technology systems</li>
      <li>oversaw curriculum and academic planning for 3-month classes</li>
      <li>led product development as a developer, designer and project manager</li>
      <li>consulted with legal counsel for compliance and risk management</li>
      <li>developed partnerships with primary and post-secondary schools</li>
    </ul>

    <h6>Chicago Apartment Finders</h6>
    <p>
      <em>Managing Broker, Chicago, IL, 2005 &mdash; 2011</em>
    </p>
    <p>
      <%= link_to 'Chicago Apartment Finders', 'http://www.chicagoapartmentfinders.com/' %>
      is an apartment broker known for its iconic marketing and boutique service. I started as
      an agent and quickly moved into management. As a Managing Broker, I trained agents,
      helped close transactions and was responsible for two branch offices.
      I'm proud to have pioneered the use of HTML-based craigslist ads, which I later helped the
      company automate with software. I also educated hundreds of landlords on
      the pitfalls of the Chicago landlord tenant ordinance. I was part of a committee with
      the Chicago Association of REALTORS that drafted and distributed a compliant lease
      to over 8,000 agents.
    </p>
    <p>
      Here's what I did on any given day:
    </p>
    <ul class="push-1">
      <li>trained new agents on best practices, the MLS and digital advertising</li>
      <li>coached agents on contracts, negotations, prospecting and risk management</li>
      <li>helped founders with business development</li>
      <li>managed payroll for sales commissions</li>
      <li>maintained compliance with rapidly changing State and local laws</li>
      <li>built relationships with landlords and property management companies</li>
    </ul>

    <h6>Day Trader</h6>
    <p>
      <em>Self-employed, Chicago, IL, 2001 &mdash; 2004</em>
    </p>
    <p>
      As a day trader, I generated my own income trading stock and option.
      On any given day, I executed trades, analyzed market data for
      alternative positioning, formulated long-term liquidity strategies
      and developed mitigation activities to hedge risk.
    </p>

    <h4>Education</h4>

    <h6>University of Michigan, Ann Arbor, Michigan</h6>
    <p>
      <em>Bachelor of Science, Economics, 1997 &mdash; 2001</em>
    </p>

    <h6>DeVry University</h6>
    <p>
      <em>Computer Information Systems, Web Development & Administration, 2011</em>
    </p>

    <h4>About me</h4>
    <p>
      I work with others in a way that's collaborative and feedback-oriented.
      I advocate a workplace culture that values ownership and productivity
      by developing effective work relationships, setting clear expectations
      and having everyone accountable for their responsibilities.
      I move fast and believe that done is better than perfect.
    </p>
    <p>
      I'm looking for a long-term opportunity, but am open to a short-term engagement to test the waters.
      If I can add value to your organization, I'm happy to start a conversation.
    </p>

  </div>

  <div class='small-1 large-2 columns'></div>

</div>

<br>
<br>
<br>
<br>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :permalink %>
    <%= f.text_field :permalink %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>

  <div class='show-for-small small-12 small-centered columns'>
    <h4 class='post-title'><%= link_to post.title, permalink_path(permalink: post.permalink) %></h4>
    <h6 class='post-date'><%= "Written on #{post.created_at.strftime('%B %e, %Y')}" %></h6>
    <%= markdown.render(post.content).html_safe %>
    <% if logged_in? %>
        <%= link_to 'Edit post', edit_post_path(post) %>
    <% end %>
  </div>

  <div class='show-for-medium large-9 large-centered columns'>
    <h3 class='post-title'><%= link_to post.title, permalink_path(permalink: post.permalink) %></h3>
    <h5 class='post-date'><%= "Written on #{post.created_at.strftime('%B %e, %Y')}" %></h5>
    <%= markdown.render(post.content).html_safe %>
    <% if logged_in? %>
        <%= link_to 'Edit post', edit_post_path(post) %>
    <% end %>
  </div>

  <div class='show-for-large-up large-9 large-centered columns'>
    <h1 class='post-title'><%= link_to post.title, permalink_path(permalink: post.permalink) %></h1>
    <h5 class='post-date'><%= "Written on #{post.created_at.strftime('%B %e, %Y')}" %></h5>
    <%= markdown.render(post.content).html_safe %>
    <% if logged_in? %>
        <%= link_to 'Edit post', edit_post_path(post) %>
    <% end %>
  </div>

<% end %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class='show-for-small small-12 small-centered columns'>
  <h4 class='post-title'><%= link_to @post.title, permalink_path(permalink: @post.permalink) %></h4>
  <h6 class='post-date'><%= "Written on #{@post.created_at.strftime('%B %e, %Y')}" %></h6>
  <%= markdown.render(@post.content).html_safe %>
  <% if logged_in? %>
    <%= link_to 'Edit post', edit_post_path(@post) %>
  <% end %>
  <p><%= link_to 'Back to all blog posts', posts_path %></p>
</div>

<div class='show-for-medium large-9 large-centered columns'>
  <h3 class='post-title'><%= link_to @post.title, permalink_path(permalink: @post.permalink) %></h3>
  <h5 class='post-date header'><%= "Written on #{@post.created_at.strftime('%B %e, %Y')}" %></h5>
  <%= markdown.render(@post.content).html_safe %>
  <% if logged_in? %>
    <%= link_to 'Edit post', edit_post_path(@post) %>
  <% end %>
  <p><%= link_to 'Back to all blog posts', posts_path %></p>
</div>

<div class='show-for-large-up large-9 large-centered columns'>
  <h1 class='post-title'><%= link_to @post.title, permalink_path(permalink: @post.permalink) %></h1>
  <h5 class='post-date header'><%= "Written on #{@post.created_at.strftime('%B %e, %Y')}" %></h5>
  <%= markdown.render(@post.content).html_safe %>
  <% if logged_in? %>
    <%= link_to 'Edit post', edit_post_path(@post) %>
  <% end %>
  <p><%= link_to 'Back to all blog posts', posts_path %></p>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password_digest %><br>
    <%= f.text_field :password_digest %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Password digest</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= user.password_digest %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>